# Generated by Django 3.1.1 on 2020-10-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='hasvideos',
            field=models.IntegerField(default=0),
        ),
    ]
